package daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARD_ITEM".
 */
public class CardItem {

    private Long id;
    private String icon_add;
    private String news_add;
    private String title;
    private java.util.Date date;

    public CardItem() {
    }

    public CardItem(Long id) {
        this.id = id;
    }

    public CardItem(Long id, String icon_add, String news_add, String title, java.util.Date date) {
        this.id = id;
        this.icon_add = icon_add;
        this.news_add = news_add;
        this.title = title;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIcon_add() {
        return icon_add;
    }

    public void setIcon_add(String icon_add) {
        this.icon_add = icon_add;
    }

    public String getNews_add() {
        return news_add;
    }

    public void setNews_add(String news_add) {
        this.news_add = news_add;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
