package daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import daogenerator.CardItem;

import daogenerator.CardItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardItemDaoConfig;

    private final CardItemDao cardItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardItemDaoConfig = daoConfigMap.get(CardItemDao.class).clone();
        cardItemDaoConfig.initIdentityScope(type);

        cardItemDao = new CardItemDao(cardItemDaoConfig, this);

        registerDao(CardItem.class, cardItemDao);
    }
    
    public void clear() {
        cardItemDaoConfig.getIdentityScope().clear();
    }

    public CardItemDao getCardItemDao() {
        return cardItemDao;
    }

}
